### ISSUE TITLE
Unable to take photos on Android with NS6

### ISSUE THREAD

**Issue by dpdragnev** [nstudio/nativescript-camera-plus#106]
Hello,

I am using NS Core 6.0

Here is how I initialize the camera:
```
<Cam:CameraPlus row="0" id="camPlus" loaded="camLoaded"
        galleryPickerMode="single"
        enableVideo="false"
        confirmVideo="false"
        saveToGallery="true"
        showCaptureIcon="true"
        showGalleryIcon="true"
        showToggleIcon="true"
        showFlashIcon="false"
        confirmPhotos="true"
        flashOffIcon="icon"
        autoSquareCrop="true"
        insetButtons="false"
        insetButtonsPercent="0.02"
        debug="false">
    </Cam:CameraPlus>
```

and this is the ts code:
```
import { CameraPlus } from '@nstudio/nativescript-camera-plus';
import { ImageAsset } from 'tns-core-modules/image-asset';
import { fromAsset } from 'tns-core-modules/image-source';
import { screen } from 'tns-core-modules/platform';
import { Image } from 'tns-core-modules/ui/image';
import { topmost } from 'tns-core-modules/ui/frame';
import { fromObject, Observable } from 'tns-core-modules/data/observable/observable';

var cam: CameraPlus;
var model: Observable = fromObject({
    width: 0
});
var closeCallback: any;

export function onShownModally(args) {
    closeCallback = args.closeCallback;
}

export function onLoaded(args: any) {

    cam = args.object.getViewById('camPlus') as CameraPlus;

    cam.on(CameraPlus.errorEvent, args => {
        console.log('*** CameraPlus errorEvent ***', args);
    });

    cam.on(CameraPlus.photoCapturedEvent, (args: any) => {
        console.log(`photoCapturedEvent listener on main-view-model.ts  ${args}`);
        console.log((<any>args).data);
        fromAsset((<any>args).data).then(res => {
            closeCallback(res);
        });
    });

    cam.on(CameraPlus.imagesSelectedEvent, (args: any) => {
        console.log(`imagesSelectedEvent listener on main-view-model.ts ${args}`);
        //console.dir(args);
        closeCallback(args.data);
    });

    const width: number = screen.mainScreen.widthDIPs - 40;
    model.set('width', width);

    args.object.bindingContext = model;
}

export function camLoaded(args: any) {
    console.log(`cam loaded event`);
    try {
        const flashMode = args.object.getFlashMode();
        console.log(`flashMode in loaded event = ${flashMode}`);
    } catch (e) {
        console.log(e);
    }
}

export function back() {
    closeCallback(null);
}

```

I am able to pick an image from the Gallery, but I cannot take a picture.  When I press the button the picture freezes, which I assume means that a photo was captured, but the event does not fire, the confirmation never comes up and the photo is never saved to the Gallery.

I am testing on a physical device.

Am I doing anything wrong?

Thanks.

**Comment by francoisph** [comment]
@dpdragnev I have the same issue, the screen to save or retake a photo doesn't show after called the takePicture function and the event photoCapturedEvent doesn't fire. 

I have the same issue on the demo on my android. On iOS it works good.

**Comment by francoisph** [comment]
@dpdragnev @triniwiz It seems that the problem comes from this commit : [v3](https://github.com/naturalinsight/nativescript-camera-plus/commit/6883be9fdc75eb376ef94c681e14ef7874519bdb#diff-1a3354503de444fe988ff3193ce81f55)

I'm using a fork from the previous commit [fix(android): video orientation ](https://github.com/naturalinsight/nativescript-camera-plus/commit/1a15e1e5f7888a3c8bdc894a6040deee1e3c0076#diff-1a3354503de444fe988ff3193ce81f55) it works I can take picture on Android.

**Comment by triniwiz** [comment]
@francoisph feel free to try the latest update 😉

**Comment by triniwiz** [comment]
@francoisph if it's android you can try the latest version 😉

**Comment by dpdragnev** [comment]
@triniwiz I am testing on Android and I just got the latest version (3.0.3), but I am still having the same issue.  The camera seems to take a picture, but the confirm dialog never shows up and I cannot continue.

**Comment by triniwiz** [comment]
I'm gonna need a way to repo .... the core demo works so 😕

**Comment by dpdragnev** [comment]
I will try to create one.  Meanwhile, are you aware of any conflicts with other plugins?  Here is my package.json.  Maybe you will spot something?

```
{
  "nativescript": {
    "id": "",
    "tns-ios": {
      "version": "6.1.0"
    },
    "tns-android": {
      "version": "6.0.2"
    }
  },
  "main": "app.js",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nstudio/nativescript-camera-plus": "^3.0.3",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "nativescript-contacts": "^1.6.2",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-masked-text-field": "4.0.3",
    "nativescript-permissions": "^1.3.8",
    "nativescript-theme-core": "2.0.5",
    "tns-core-modules": "6.0.6",
    "tns-platform-declarations": "^6.1.1"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "1.2.0",
    "typescript": "3.4.5"
  },
  "gitHead": "",
  "readme": "NativeScript Application"
}

```

Thank you

**Comment by triniwiz** [comment]
No but you may want to match the core modules version an the runtime

**Comment by dpdragnev** [comment]
@triniwiz,  I just downloaded the demo and tried it on my device and I get the same result.  The screen freezes as if the picture was taken, but I do not get a confirmation popup and the picture is not in the gallery.

I am testing on a physical device with Android v.7.0 installed.

**Comment by dpdragnev** [comment]
When I try the same on my Node 9, everything works well.

**Comment by vicmasa** [comment]
I have the same problem, you cannot take photos with the takePicture event, and the event is not detected.
I enclose a project where I could isolate the error.
https://github.com/vicmasa/testbg
Greetings.

**Comment by zoocreative** [comment]
@dpdragnev did you ever find a solution to this?

**Comment by aosi87** [comment]
Still an issue, S10(Android 10), my old Moto 5E works fine tho.

**Comment by triniwiz** [comment]
Fixed: https://github.com/nstudio/nativescript-camera-plus/commit/b24997c918df8ceafb73443708a58708be46d5ed feel free to reopen :- update to `3.1.x`
