### ISSUE TITLE
help! error select single.

### ISSUE THREAD

**Issue by srcarmi** [nstudio/nativescript-camera-plus#107]
Error getting image source:
Asset cannot be found.

 this.imageSource.fromAsset(imageAsset).then(
          imgSrc => {
            if (imgSrc) {
              this.zone.run(() => {
                this.imageSource = imgSrc;
              });
              console.log(this.imageSource);
            } else {
              this.imageSource = null;
              this.selectFile = false;
              alert('Image source is bad.');
            }
          },
          err => {
            this.imageSource = null;
            this.selectFile = false;
            console.log('Error getting image source: ');
            console.error(err);
            alert('Error getting image source from asset');
          }
        );

**Comment by Sartori-RIA** [comment]
same here, I trying this way and getting same error only to iOS 13.x

```typescript

export class ImagePickerComponent implements OnInit {

    ngOnInit() {
        this.camera = new CameraPlus();
    }


   onChosePicture() {
        this.camera.galleryPickerMode = 'single';
        this.camera.debug = true;
        this.camera.chooseFromLibrary({
            showImages: true,
            showVideos: false,
            keepAspectRatio: true
        }).then((picture: ImageAsset[]) => {
            this.setChooseImage(picture[0]);
        }).catch((e) => {
            console.log('Error: ', e)
        });
    }


    setChooseImage(selected: ImageAsset) {

       const image = new ImageSource();
       image.fromAsset(selected).then((imageSource) => {
           const tempPhoto = `${knownFolders.temp().path}/${new Date().getTime()}.jpeg`;
           if (imageSource.saveToFile(tempPhoto, 'jpeg')) {
               console.log('finally works')
           }
       }).catch((er) => {
           console.log(er);
       })
   }
}

```

**Comment by Logikgate** [comment]
We are also having this issue only on iOS 13.   It occurs when picking any image from the gallery and then trying to get the ImageSource of the returned ImageAsset
