### ISSUE TITLE
Use of co.fitcom.fancycamera.FancyCamera

### ISSUE THREAD

**Issue by madmansn0w** [nstudio/nativescript-camera-plus#108]
There's a problem using nativescript-camera-plus with android.speech.SpeechRecognizer due to the fact that co.fitcom.fancycamera.FancyCamera is used by camera-plus, which in turn builds MediaRecorder and that uses both manifest permissions AUDIO_RECORD and CAMERA. Since SpeechRecognizer needs to use the audio source, it causes a conflict and only one library can be used at a time. 

I would like some help figuring out how to go about handling this issue. It took me a while to identify where the problem was, but I'm like 90% sure that's what is going on here. 

in camera-plus.android.js => **this._camera = new co.fitcom.fancycamera.FancyCamera(this._context);**

```java 
CameraPlus.prototype.createNativeView = function () {
     app.android.on('activityRequestPermissions', this._permissionListener);
     this._nativeView = new android.widget.RelativeLayout(this._context);
     this._camera = new co.fitcom.fancycamera.FancyCamera(this._context);
     CameraOrientation.values()[0]);
     this._camera.setLayoutParams(new android.view.ViewGroup.LayoutParams(android.view.ViewGroup.LayoutParams.MATCH_PARENT, android.view.ViewGroup.LayoutParams.MATCH_PARENT));
     this._nativeView.addView(this._camera);
     return this._nativeView;
};
```
I would like to change this to just use a camera instance without creating audio buffer channel conflicts. 

Any suggestions? A separation of resources would be ideal for FancyCamera, but that needs to be submitted over there.

**Comment by triniwiz** [comment]
This issue would need to be addressed in the lib ..... it uses the recorder to check for mic lvls an atm it's not configurable

**Comment by madmansn0w** [comment]
Do you have any idea how I would go about customizing the library for my needs?

Or if that's going to require a big mess of changes, perhaps it's easier to copy the audio buffer to an array that can be shared with different resources?

**Comment by triniwiz** [comment]
fixed: https://github.com/nstudio/nativescript-camera-plus/commit/ed68850e5ccfe14669f51fa074401c5bb0b6f635

**Comment by madmansn0w** [comment]
You're incredible!
