### ISSUE TITLE
Demo angular fails to build

### ISSUE THREAD

**Issue by Noppey** [nstudio/nativescript-camera-plus#111]
Just downloaded the zip, opened the src directory with VS code: npm run demo.ng.android.device

ERROR in C:/Users/Administrator/source/repos/nativescript-camera-plus-master/src/camera-plus.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Administrator\source\repos\nativescript-camera-plus-master\src\camera-plus.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at NativeScriptAngularCompilerPlugin.getCompiledFile (C:\Users\Administrator\source\repos\nativescript-camera-plus-master\demo-ng\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:844:23)

**Comment by bradmartin** [comment]
Corrected this issue. Thanks for reporting.
