### ISSUE TITLE
takePicture does not generate event

### ISSUE THREAD

**Issue by vicmasa** [nstudio/nativescript-camera-plus#115]
Hello everyone, when invoking "take Picture", the event is not detected and images and videos cannot be captured.
I enclose an isolated project where you can see the error.
Greetings.
https://github.com/vicmasa/testbg

**Comment by omarjavierr277** [comment]
takePicture does not generate event

**Comment by wili525186** [comment]
It does not work for me either

**Comment by zoocreative** [comment]
Has anyone had any luck with this? I am getting the same problem. It works on the emulator but not on my phone. It doesn't seem to fire the 'photoCapturedEvent' so I am guessing something is going wrong before that is done.

**Comment by sublime392** [comment]
I am now experiencing the same problem after updating to Angular 9.  The `"CameraPlus takePic options"` gets logged, but the `photoCapturedEvent` does not happen. Interestingly, I have a modal that gets displayed over the camera with some instructions for the user. The photo capture event works just fine after displaying and dismissing that modal.

**Comment by vicmasa** [comment]
Solution: Call the event only once

exports.camLoaded = function (args) {
    console.log(`cam loaded event`);
    try {
        cam = args.object;
        if (isInit) {
            isInit = false;
            console.log('NEW LISTENER');
            cam.on(CameraPlus.photoCapturedEvent, (event) => {
                onEvent(event);
            });
        }
    } catch (e) {
        console.log(e);
    }
}

**Comment by sublime392** [comment]
@vicmasa I don't think your solution is applicable to an Angular project.

**Comment by arturikoX** [comment]
Hi, the problem is still happening ..
is there any updates ?
( BTW, in IOS the capture event works )


Thanks!

**Comment by wuilmerj24** [comment]
Hi same problem. Any updates?
