### ISSUE TITLE
BufferOverflowException on new Android projects taking photo

### ISSUE THREAD

**Issue by joshcomley** [nstudio/nativescript-camera-plus#117]
Hi all,

I've copied the capture component from the sample project into a brand new, latest NS project and when I take a photo I get the following error:

	An uncaught Exception occurred on "CameraThread" thread.
	null

	StackTrace:
	java.nio.BufferOverflowException
		at java.nio.ByteBuffer.put(ByteBuffer.java:544)
		at co.fitcom.fancycamera.Camera2$1.imageToBitmap(Camera2.java:144)
		at co.fitcom.fancycamera.Camera2$1.onImageAvailable(Camera2.java:113)
		at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:658)
		at android.os.Handler.dispatchMessage(Handler.java:102)
		at android.os.Looper.loop(Looper.java:159)
		at android.os.HandlerThread.run(HandlerThread.java:61)

The same occurs in other projects.

Taking video, however, succeeds.

I tried importing what I think is the latest `co.fitcom.fancycamera`, but I ended up with a `Duplicate class` error with the `triniwiz` one:

    implementation 'co.fitcom:fancycamera:1.1.11'

Results in:

    Duplicate class co.fitcom.fancycamera.BuildConfig found in modules fancycamera-1.1.11-runtime.jar (co.fitcom:fancycamera:1.1.11) and fancycamera-1.2.3-runtime.jar (com.github.triniwiz:fancycamera:1.2.3)

Any ideas?

I'm using a `ASUS ZenPad 3s 10` running Android 7.0, `tns --version` yields `6.4.0` and here is my `package.json`:

	  {
		"nativescript": {
		  "id": "org.nativescript.NsCameraTest",
		  "tns-android": {
			"version": "6.4.1"
		  },
		  "tns-ios": {
			"version": "6.4.0"
		  }
		},
		"description": "NativeScript Application",
		"license": "SEE LICENSE IN <your-license-filename>",
		"repository": "<fill-your-repository-here>",
		"dependencies": {
		  "@angular/animations": "~8.2.0",
		  "@angular/common": "~8.2.0",
		  "@angular/compiler": "~8.2.0",
		  "@angular/core": "~8.2.0",
		  "@angular/forms": "~8.2.0",
		  "@angular/platform-browser": "~8.2.0",
		  "@angular/platform-browser-dynamic": "~8.2.0",
		  "@angular/router": "~8.2.0",
		  "@nativescript/theme": "~2.3.0",
		  "@nstudio/nativescript-camera-plus": "^3.0.5",
		  "nativescript-angular": "~8.21.0",
		  "node-sass": "^4.13.1",
		  "reflect-metadata": "~0.1.12",
		  "rxjs": "^6.4.0",
		  "tns-core-modules": "~6.4.0",
		  "zone.js": "~0.9.1"
		},
		"devDependencies": {
		  "@angular/compiler-cli": "~8.2.0",
		  "@ngtools/webpack": "~8.2.0",
		  "nativescript-dev-webpack": "~1.5.0",
		  "typescript": "~3.5.3"
		},
		"gitHead": "d8bdf0799a219051f28f8abd7c258d2bf2fce6e1",
		"readme": "NativeScript Application"
	  }

**Comment by joshcomley** [comment]
Incidentally, the same happens with the following settings:

    this.cam.takePicture({ saveToGallery: true, width: 300, height: 300 });

And:

    this.cam.takePicture({ saveToGallery: false, width: 300, height: 300 });

And all combinations I've tried.

**Comment by joshcomley** [comment]
If I replace `src\platforms\android\include.gradle` with:

    allprojects {
        repositories {
            maven { url "https://jitpack.io" }
            google()
        }
    }
    dependencies {
    implementation "com.android.support:exifinterface:+"
        // implementation 'com.github.triniwiz:fancycamera:1.2.3'
        implementation 'co.fitcom:fancycamera:1.1.11'
    }

Taking a photo works again, but the preview is incorrect dimensions, presumably because the custom `triniwiz` implementation has some useful stuff in that area.

**Comment by RGBvision** [comment]
Just found that current version of triniwiz/fancycamera is 1.2.2. So try to change to `implementation 'com.github.triniwiz:fancycamera:1.2.2'`

**Comment by joshcomley** [comment]
Still getting this issue - any suggestions?

**Comment by bradmartin** [comment]
I haven't had time to look at this in a while. So updating the dep of the `exifinterface` fixed the overflow but now dimensions are incorrect? If so, we might just bump Osei's library and see how many changes are needed for the dimension changes (usually not fun :/)

**Comment by bradmartin** [comment]
If you're familiar with android libraries, possibly forking Osei's lib and updating the deps, running the demo app (think it includes a demo of the camera) and then seeing if the dimensions are correct or if the sizing needs adjusted would be where I would start.

**Comment by triniwiz** [comment]
@joshcomley I pretty much moved to use the new CameraX lib which handles a lot of edges cases that would be hard to catch/fix w/o the actual device so the 1.x support is pretty limited

**Comment by triniwiz** [comment]
Fixed on the latest
