### ISSUE TITLE
iOS issues with QBImagePicker

### ISSUE THREAD

**Issue by Logikgate** [nstudio/nativescript-camera-plus#118]
QBImagePicker hasn't been updated in years and it appears the maintainer has no interest in merging in pull requests from the community.

QBImagePicker does not work correctly with iOS13 or with dark mode.  We have forked it [here](https://github.com/flypapertech/QBImagePicker) and have merged in the the two community pull requests to fix these issues.  We plan to maintain this fork for use with nativescript-camera-plus.  

For now we are using our own fork of nativescript-camera-plus so that we can depend on our fork of QBImagePicker.  Would you be open to a pull request that updates this repo to use our fork?

**Comment by bradmartin** [comment]
Absolutely, if it's working well then no issue using a fork of it. Do you mind sending a PR with the POD pointing to your forked version so we can build and run it before merging and publishing?
