### ISSUE TITLE
"attribute android:requestLegacyExternalStorage not found."

### ISSUE THREAD

**Issue by joshcomley** [nstudio/nativescript-camera-plus#120]
If I create a new, blank NS app, run `tns plugin add @nstudio/nativescript-camera-plus` and then `tns run android`, I get the following build error:

	Execution failed for task ':app:processDebugResources'.
	Android resource linking failed
	D:\Code\Playgrounds\NsCameraTest2\platforms\android\app\src\main\AndroidManifest.xml:17:2-38:16: AAPT: error: attribute android:requestLegacyExternalStorage not found.

	Command gradlew.bat failed with exit code 1

This is because `node_modules\@nstudio\nativescript-camera-plus\platforms\android\nativescript_camera_plus.aar\AndroidManifest.xml` contains `android:requestLegacyExternalStorage="true"`, which is no longer supported in later APIs.

**Comment by calleja23** [comment]
https://stackoverflow.com/questions/58976425/aapt-error-attribute-androidrequestlegacyexternalstorage-not-found
in your app.graddle

  defaultConfig {
    minSdkVersion 17
    versionCode 8
    generatedDensities = []
    compileSdkVersion 29

  }

**Comment by joshcomley** [comment]
This did resolve this particular issue for me, thank you
