### ISSUE TITLE
Android: Exposure issues

### ISSUE THREAD

**Issue by matty0005** [nstudio/nativescript-camera-plus#121]
Hi, 
I've been implementing this plugin and noted that on my Lenovo tablet, the exposure is more or less locked. If its relatively dark, the image results in a very dark image. Furthermore, if I go outside, I get just a white image. There are only a few times that I can get a decent image out of it.  If I use the built-in camera app with the tablet, the images come out just fine.

Additionally, while using my Samsung Galaxy S8, I have no problems with either scenario - the image adjusts to the light levels.

Is there any way that this issue can be fixed in software, or is it purely hardware.

**Comment by triniwiz** [comment]
I exposed the whiteBalance in the latest update feel free to lmk if you need more settings
