### ISSUE TITLE
The photoCapturedEvent event does not work on physical devices.

### ISSUE THREAD

**Issue by vicmasa** [nstudio/nativescript-camera-plus#131]
Hi. The **photoCapturedEvent** works well on Android virtual machines, but when we test on physical devices, the event only occurs a few times, you can see the attached video, where in TAP 17 the image is just captured. I am using a Huawei P20 PRO.

I was able to separate the bug into a clean project, you can clone it from:
https://github.com/vicmasa/ns-camera-plus-vanilla.git

See Video
https://invian-sources.s3.amazonaws.com/tmp/bugs/bug_cameraPlus_01.mp4

**Comment by Arturiko** [comment]
Same as #115 and #106 ...

**Comment by triniwiz** [comment]
Fixed: https://github.com/nstudio/nativescript-camera-plus/commit/b24997c918df8ceafb73443708a58708be46d5ed feel free to reopen :- update to `3.1.x`
