### ISSUE TITLE
Android preview and picture taken show different scale/zoom/dimensions

### ISSUE THREAD

**Issue by Murilo-Perrone** [nstudio/nativescript-camera-plus#143]
I can't take pictures properly in my Nativescript-Android project using `nativescript-camera-plus`. I have tried everything possible from my side. Might be a bug in fancycamera component?

Up to v3.0.8 (uses fancycamera 1.2.3):
- The camera preview (before the picture is taken) is zoomed (aprox 2x zoom), hiding a large extension of viewable area.
- The picture taken then showed a much larger area (which is correct, the maximum area the camera can capture).

![Screen Shot 2020-12-11 at 12 33 26 PM](https://user-images.githubusercontent.com/26028390/101922706-30db6e00-3bad-11eb-9b25-02e4a5a34052.png)

Now in v3.1.0 (uses fancycamera 3.0.0-alpha13):
- The camera preview now is working OK, showing the full visible area.
- However, the picture taken now gets cropped in top and bottom, until the ratio is inverted (3:4 to 4:3).

![Screen Shot 2020-12-11 at 12 33 41 PM](https://user-images.githubusercontent.com/26028390/101922743-3df85d00-3bad-11eb-8261-a554aa2089f1.png)

For instance, I'm using portrait 3:4 view, expecting a portrait picture with maximum resolution (3024x4032 photo). But v3.1.0 crops it down into a 3024x2268 landscape image.

Sample code:

```typescript
import { screen, ScreenMetrics } from "tns-core-modules/platform/platform";
...
  ngOnInit(): void {
    const m: ScreenMetrics = screen.mainScreen;
    this.metrics = {
      widthDIPs: m.widthDIPs,
      heightDIPs: m.heightDIPs,
      ...
    };
  }
```

```xml
        <CameraPlus
            width="{{metrics.widthDIPs}}"
            height="{{metrics.widthDIPs * (4/3)}}"
            ...
            (photoCapturedEvent)="photoCapturedEvent($event)"
            (loaded)="camLoaded($event)">
        </CameraPlus>
```
Logs:
```
Camera width: 392.72727272727275, height:523.6363636363636, scaleX: 1, scaleY:1
Screen metrics:
{
  "widthPixels": 1080,
  "heightPixels": 2160,
  "widthDIPs": 392.72727272727275,
  "heightDIPs": 785.4545454545455,
  "scale": 2.75
}
```

Is there any workaround? I noticed the same problem also affects demo-ng...

**Comment by triniwiz** [comment]
By default the camera uses the preview ratio `4:3` now , it will choose the largest photo size of `4:3` available for the current camera on the device however you can now customize both.

 First you will need to get the supported preview ratios by calling `cameraPlusInstance.getGetSupportedRatios()` it returns an array of the supported preview ratios which can be passed to `cameraPlusInstance.ratio` next you will need to set a `pictureSize` of your liking or allow the system will use the largest size of the chosen ratio .

 To get an array of the picture sizes the currently open camera supports you will need to call the following passing the ratio you previously got ` cameraPlusInstance.getAvailablePictureSize(currentRatio)` it will return an array of the supported picture sizes of that ratio that u can set `cameraPlusInstance.pictureSize` <- also you can get the current `pictureSize`

**Comment by Murilo-Perrone** [comment]
Thanks for your quick response. I had already explored those new methods, but they don't help. Because all acceptable rations require the width to be greater than the height, so `3:4` would not be a valid ratio. I'm actually just using a regular `4:3` but it is rotated because of phone's is in `PORTRAIT` position. The preview understands that, but the image capture doesn't seem. It needs to take a regular landscape picture then rotate it.

```typescript
    const ratio = "3:4";
    this.cam.ratio = ratio; // won't accept this value
    this.cam.pictureSize = "3024x4032"; // value not accepted again
    const size = this.cam.getAvailablePictureSizes(ratio)[0];
    this.cam.pictureSize = size.height + "x" + size.width; // trying to invert them, no luck
```
I even tried changing the orientation directly in fancycam:

```typescript
    const fancycamera = (<any>this.cam)._camera;
    fancycamera.setCameraOrientation(com.github.triniwiz.fancycamera.CameraOrientation.PORTRAIT); // value is accepted, but that won't fix the problem
    fancycamera.setRatio("3:4"); // won't accept that value
```

Where is the code that does this image crop? Is it in fancycam or in android SDK?

**Comment by triniwiz** [comment]
it's behaving as it should you are doing the correct thing but I missed updating the internal call from that method [here](https://github.com/triniwiz/fancycamera/blob/master/fancycamera/src/main/java/com/github/triniwiz/fancycamera/FancyCamera.kt#L128) that needs to call `cameraView.rotation = orientation ` you should be able to access the internal class by doing `this._camera.getChildAt(0)` then calling `.setRotation(com.github.triniwiz.fancycamera.CameraOrientation.PORTRAIT)` it will take the photo as you like also you should use the `fancycamera.setRatio("4:3");` 


```ts
    const fancycamera = (<any>this.cam)._camera;
    const internalCamera = fancycamera.getChildAt(0);
    internalCamera.setCameraOrientation(com.github.triniwiz.fancycamera.CameraOrientation.PORTRAIT); // value is accepted, and should take effect
    fancycamera.setRatio("4:3"); 
```

I'll try getting a new release out with the fix also the cropping is done [here](https://github.com/triniwiz/fancycamera/blob/master/fancycamera/src/main/java/com/github/triniwiz/fancycamera/Camera2.kt#L998)  and [here](https://github.com/triniwiz/fancycamera/blob/master/fancycamera/src/main/java/com/github/triniwiz/fancycamera/Camera.kt#L618)

**Comment by Murilo-Perrone** [comment]
Thanks again for your quick response. Setting internal camera orientation fixed the cropping issue:

```typescript
const fancycamera = (<any>this.cam)._camera;
const internalCamera = fancycamera.getChildAt(0);
internalCamera.setRotation(com.github.triniwiz.fancycamera.CameraOrientation.PORTRAIT);
```

However, the image I got was missing a 90 degree rotation. This is because [rotation code](https://github.com/triniwiz/fancycamera/blob/master/fancycamera/src/main/java/com/github/triniwiz/fancycamera/Camera2.kt#L1012-1040) is only present in the `if (autoSquareCrop)` block, and not in the `else` block. Though I'm not using `autoSquareCrop` because I don't want a squared image. Hence, it seems the cropping was not being done by the internal camera class, but rather by android's [`ImageCapture`](https://developer.android.com/reference/androidx/camera/core/ImageCapture#takePicture(androidx.camera.core.ImageCapture.OutputFileOptions,%20java.util.concurrent.Executor,%20androidx.camera.core.ImageCapture.OnImageSavedCallback)) class. 

To wipe out the bugs, I suggest eliminating all repeated code in [Camera2.takePhoto()](https://github.com/triniwiz/fancycamera/blob/14f3816d6eb162c5db641385c0c17cce7ab843ae/fancycamera/src/main/java/com/github/triniwiz/fancycamera/Camera2.kt#L966). This means having a single sequence of code with the `imageCapture.takePicture` call, aided with a few `if (autoSquareCrop)` statements inside it. Today it has a large `if (autoSquareCrop)` block that does it all and then the code is repeated in the `else` block but it missed replicating some steps.

Also, if orientation/ratio/pictureSize method names in FancyCamera and internal camera can be the same, then I suggest making an interface to use kotlin's implementation of [Delegation Pattern](https://kotlinlang.org/docs/reference/delegation.html), to eliminate proxy code and avoid such bugs. (I would have forked it to make that contribution if the project had builded first try, but that wasn't the case)

Meanwhile this is not fixed, I'm doing the pending image rotation via CSS `rotate: 90;` plus using some crazy calculations and hacks to display it properly. 8-)

PS: the issue is also visible in demo app.

**Comment by Murilo-Perrone** [comment]
Fixes are on the way ([fancycam#12](https://github.com/triniwiz/fancycamera/issues/12)). They work with app that starts in any of the 4 possible orientations (portrait, landscape, landscape reverset or portrait reversed).

However, for a unlocked app, the switching between orientations in runtime is not yet. That's because the App "flips" aren't being detected and thus fancycamera isn't reacting to them. Fancycamera listens to [`addOnDestinationChangedListener`](https://developer.android.com/guide/navigation/navigation-ui), but not what we need, since it's independent from the view rotation.

A client workaround is to map `"orientationChanged"` event, which can be tried in the demo code:
```TS
constructor(...) {
  on("orientationChanged",  (evt) => {
    setTimeout(() => this.onOrientationChanged(evt.eventName, evt.newValue), 1000) // Restart preview
  });
}
onOrientationChanged(eventName: string, newValue: string) {
  if (isAndroid && this.cam) {
    const fancyCamera = (<any>this.cam)._camera as com.github.triniwiz.fancycamera.FancyCamera;
    fancyCamera.stopPreview();
    setTimeout(() => fancyCamera.startPreview(), 1000);
  }
```

Tried to move this into the plugin's code n `initNativeView` method, but the orientation event won't be triggered when mapped from there. Then I noticed there is an alternative event registered in `camera-plus.android.ts`:
```TS
initNativeView() {
  super.initNativeView();
  this.on(View.layoutChangedEvent, this._onLayoutChangeListener);
```

Oddly enough, the `"layoutChanged"` event was also not being triggered for Android/angular. And mapping this event from client code also didn't work. Problems with iOS have also been registered before: https://gitmemory.com/issue/NativeScript/NativeScript/7085/494258757

Happily, I found out a native workaround. Not pretty, but works:
```TS
private layoutChangeListener = new android.view.View.OnLayoutChangeListener( {
  onLayoutChange (v: android.view.View, left:number, top:number, right:number, bottom:number, oldLeft:number, oldTop:number, oldRight:number, oldBottom:number):any {
      if (left != oldLeft || top != oldTop || right != oldRight || bottom != oldBottom) {
          console.log(`OnLayoutChangeListener left:${oldLeft}->${left}, top:${oldTop}->${top}, right:${oldRight}->${right}, bottom:${oldBottom}->${bottom}`);
          eval("_this._onLayoutChangeFn()");
      }
  }
});

initNativeView() {
  super.initNativeView();
  this.nativeView.addOnLayoutChangeListener(this.layoutChangeListener);
  ...
}
...
disposeNativeView() {
  this.nativeView.removeOnLayoutChangeListener(this.layoutChangeListener);
```

With that, `CameraPlus._onLayoutChangeFn` can be used to trigger an update on Fancycamera. Is that the best approach?

**Comment by Murilo-Perrone** [comment]
Found out the best approach which was to use [`onConfigurationChanged`](https://github.com/Murilo-Perrone/fancycamera/blob/96d43e05bc294bfcbf08650d3d10f7cf222cf2c0/fancycamera/src/main/java/com/github/triniwiz/fancycamera/Camera2.kt#L326) within `Camera2.kt` from FancyCamera to update the `ImageCapture` target rotation. I think that was the last fix needed for correct image capturing. 🥳

**Comment by Murilo-Perrone** [comment]
Fixed through an update in fancycamera dependency (was missing portrait adjustment for ImageCapture targets).
