### ISSUE TITLE
Cannot get demo to work

### ISSUE THREAD

**Issue by jtkeyva** [nstudio/nativescript-camera-plus#17]
I've tried using Sidekick, the command line and Xcode but I just can't get it to build and run. I have gotten it to the point where I see the splash screen but that's it. Any ideas or help appreciated.
Thanks

**Comment by bradmartin** [comment]
I'd recommend the CLI, there are a few scripts in the package.json that you
can look at to get the demo working. Without any error my first guess for
developers is they don't have the actual .js output from transpiling the
TS. You can manually run tsc on the src or check the scripts for a helper
that might have this in it also. I'll double check later but if you have
any errors that will help a lot. Thanks

**Comment by jtkeyva** [comment]
Thanks. I got the following error:

JS ERROR Error: Could not find module '@nstudio/nativescript-camera-plus'. Computed path '/var/mobile/Containers/Data/Application/D0866C4A-XXXX-XXXX-XXXX-830C19DFEA54/Library/Application Support/LiveSync/app/tns_modules/@nstudio/nativescript-camera-plus'

Any help appreciated!

**Comment by bradmartin** [comment]
Try pathing into the `src` directory in your terminal, then running `npm run tsc && npm run demo.android` this should transpile the ts files and then prep the plain NS demo and run it on android (emulator or device if connected). Let me know if that helps any.

**Comment by bradmartin** [comment]
Looks like I need to update the documentation on running the demo and clean things up some, sorry for any confusion on the README, we published this in a hurry one day 😄

**Comment by jtkeyva** [comment]
Thanks. I went into src directory and did npm run tsc && npm run demo.ios  and got this:

> @nstudio/nativescript-camera-plus@1.0.2 tsc /Users/jt/Code/nativescript/cam4/nativescript-camera-plus/src
> tsc -skipLibCheck

sh: tsc: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @nstudio/nativescript-camera-plus@1.0.2 tsc: `tsc -skipLibCheck`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @nstudio/nativescript-camera-plus@1.0.2 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm run tsc && npm run demo.android
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jt/.npm/_logs/2018-04-12T02_26_39_671Z-debug.log

**Comment by bradmartin** [comment]
ah first run `npm i`, my fault. Assumed you had typescript installed globally or already had the node_modules init'd

**Comment by bradmartin** [comment]
Make sure to set the prop https://github.com/nstudio/nativescript-camera-plus/blob/master/demo/app/main-page.xml#L16 in the template or in code if you have an instance of the cameraplus. The demo also should have the code to start recording in the TS files for that page 👍 ping us if any thing else pops up.

**Comment by jtkeyva** [comment]
It was set to true. Not sure what you mean by "The demo also should have the code to start recording in the TS files for that page"

**Comment by bradmartin** [comment]
https://github.com/nstudio/nativescript-camera-plus/blob/master/demo/app/main-view-model.ts#L66

**Comment by jtkeyva** [comment]
Right, yes it's there. I noticed there is no "record" method in the readme. Does that mean it's not implemented?
Thanks for your help and patience

**Comment by jtkeyva** [comment]
@bradmartin Still unable to get a video to record. Any ideas?
Thanks!

**Comment by jtkeyva** [comment]
@bradmartin don't mean to bother you so much, but I'm still unable to record video and have no clue on how to proceed. Any help greatly appreciated

**Comment by bradmartin** [comment]
what device are you testing on?

**Comment by jtkeyva** [comment]
I'm testing on an iPhone X. I can see video but pressing record doesn't seem to do anything
thanks alot!

**Comment by bradmartin** [comment]
Unfortunately, I only have an iPhone6 I test with. After ngConf this week, Nathan Walker (speaking/presenting at the conference), is far more familiar with the iOS implementation since he did it originally, I think he plans to look at some of the iOS issues on the repo. I will check my iPhone6 tomorrow when I have it near me 😄 thanks for being patient.  In the meantime, are you able to record on android, should be possible with android emulators to record via the webcam. I pushed version 1.0.4 earlier today that fixed some minor android issues and it seemed to all work on my Pixel2 and a couple emulators.

**Comment by flinbu** [comment]
Hi there, I got error trying to run demo on iPhone 8 Plus (iOS 13.1):

The log:
```
> Module '@nstudio/nativescript-camera-plus' not found for element '@nstudio/nativescript-camera-plus:CameraPlus'.
> This value is not a native object.
NativeScript caught signal 11.
Native Stack:
1   0x10f84484f sig_handler(int)
2   0x7fff518c9b1d _sigtramp
3   0x0
4   0x7fff518fdb85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x7fff51901e58 _Unwind_RaiseException
6   0x7fff4f6df8bd __cxa_throw
7   0x7fff50864c44 _objc_exception_destructor(void*)
8   0x10f7ffd58 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
9   0x10f837b60 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
10  0x1101d8dd6 ffi_closure_unix64_inner
11  0x1101d97fa ffi_closure_unix64
12  0x7fff23ad3875 _CFXRegistrationPost1
13  0x7fff23ad35e1 ___CFXNotificationPost_block_invoke
14  0x7fff23bd1a33 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
15  0x7fff23ad2f36 _CFXNotificationPost
16  0x7fff25676cb5 -[NSNotificationCenter postNotificationName:object:userInfo:]
17  0x7fff47571581 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]
18  0x7fff47576f6e -[UIApplication _runWithMainScene:transitionContext:completion:]
19  0x7fff46cbc3ed -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]
20  0x7fff471a4aa9 _UIScenePerformActionsWithLifecycleActionMask
21  0x7fff46cbceff __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
22  0x7fff46cbc90e -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
23  0x7fff46cbcd2c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
24  0x7fff46cbc5c1 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
25  0x7fff46cc0bef __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2
26  0x7fff470ca9d7 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
27  0x7fff471c2fa7 _UISceneSettingsDiffActionPerformChangesWithTransitionContext
28  0x7fff46cc090a __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
29  0x7fff471c2eaa _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext
30  0x7fff46cc0778 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
31  0x7fff46b1ac67 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
JS Stack:
1   UIApplicationMain@[native code]
2   _start@file:///node_modules/tns-core-modules/application/application.js:277:0
3   run@file:///node_modules/tns-core-modules/application/application.js:305:0
4   @file:///app/bundle.js:1682:65
5   ./app.ts@file:///app/bundle.js:1694:34
6   __webpack_require__@file:///app/webpack/bootstrap:750:0
7   checkDeferredModules@file:///app/webpack/bootstrap:43:0
8   webpackJsonpCallback@file:///app/webpack/bootstrap:30:0
9   anonymous@file:///app/bundle.js:2:61
10  evaluate@[native code]
11  moduleEvaluation@:1:11
12  promiseReactionJob@:1:11
```
Any idea about this?

Thanks!
