### ISSUE TITLE
Invalid camera object in loaded event

### ISSUE THREAD

**Issue by kryzys69** [nstudio/nativescript-camera-plus#19]
I don't know why I have invalid object in _loaded_ event. It doesn't have any methods, that CameraPlus should have...

```
public camLoaded(e: any): void {
  console.log('***** cam loaded *****');
  this.cam = e.object as CameraPlus;
  let flashMode = this.cam.getFlashMode();
  ...
```

I've got:
`ERROR TypeError: this.cam.getFlashMode is not a function`

`this.cam` object looks like a `view`, but it is not camera :|

It behaves the same in Genymotion emulator and real device.

**Comment by bradmartin** [comment]
What's your template look like?

**Comment by kryzys69** [comment]
Damn, it was this part that was missing... I've missed:

`registerElement("CameraPlus", () => <any>CameraPlus);`

**Comment by aosi87** [comment]
This should be added to the ng-demo example, or as a comment in the README, the problem is that i was assuming that the plugin was taking care of this, similar to camera permissions. Besides this small thing, the plugin works really well, great job

tnx author.
