### ISSUE TITLE
Event object has a different interface

### ISSUE THREAD

**Issue by vasyliv** [nstudio/nativescript-camera-plus#26]
Hello everyone! Thanks for your library.
I`ve tried to make the same ng-demo as in your repository but got an error (i guess).
The object from the event that in https://github.com/vasyliv/test-nativescript-camera-plus/blob/master/app/home/home.component.ts#L32 doesn't have interface CameraPlus, it has interface ProxyViewContainer (that doesn't have method "takePicture")
![image](https://user-images.githubusercontent.com/19407350/39048806-75faeb6e-44a7-11e8-8ea7-80d44797c750.png)

**Comment by vasyliv** [comment]
a problem might be with "tns-core-modules": "4.0.0", i guess i should be 3.+

**Comment by Tallking** [comment]
I am having the same issue. The object comes up as ProxyViewContainer instead of CameraPlus hence does not have the getFlashMode() method. Have you resolved this challenge. Please what did you do. I am running angular 8 and tns-core-modules is 6.1.0

**Comment by michael-vasyliv** [comment]
@Tallking I fixed the problem by replacing the package to this one `nativescript-camera`

**Comment by Tallking** [comment]
Thank you for your reply. But I resolved it by registering the CameraPlus element using nativescript  registerElement module.
