### ISSUE TITLE
How can be worked with Nativescript-Vue

### ISSUE THREAD

**Issue by edwarchou** [nstudio/nativescript-camera-plus#34]
I use this nativescript-camera-plus with Nativescript-vue but get some mistakes, so i wondering is there any demes worked with nativescript-vue;

the way i used in native-script-vue:

import { CameraPlus } from "@nstudio/nativescript-camera-plus";
Vue.registerElement('CameraPlus', () => CameraPlus );
  <CameraPlus height="250" debug="true" 
	galleryPickerMode="single" 
	showFlashIcon="true" 
	showToggleIcon="true" 
        showCaptureIcon="true" 
	showGalleryIcon="true"
	@loaded="camLoaded($event)" 
	@toggleCameraEvent="toggleCameraEvent($event)" 
	@photoCapturedEvent="photoCapturedEvent($event)"
	@imagesSelectedEvent="imagesSelectedEvent($event)"
 >
 and the errors are:

JS: 'NativeScript-CameraPlus ---' [ 'video enabled:', false, [length]: 2 ]
JS: 'NativeScript-CameraPlus ---' [ 'default camera:', 'rear', [length]: 2 ]
JS: 'NativeScript-CameraPlus ---' [ '*** onSurfaceTextureAvailable ***
JS: this.cameraId = 0',
JS:   [length]: 1 ]
JS: 'NativeScript-CameraPlus ---' [ '*** _initCamera ***
JS: this.cameraId = 0 --- device: Google Android SDK built for x86 on SDK: 27',
JS:   [length]: 1 ]
JS: 'NativeScript-CameraPlus ---' [ 'opening camera with id = 0', [length]: 1 ]
JS: 'NativeScript-CameraPlus ---' [ 'supported focus modes = [fixed] --- device: Google Android SDK built for x86 on SDK: 27',
JS:   [length]: 1 ]
JS: 'NativeScript-CameraPlus ---' [ '*** _setCameraDisplayOrientation ***', [length]: 1 ]
JS: 'NativeScript-CameraPlus ---' [ 'error _initCamera',
JS:   [TypeError: Cannot read property 'getWindowManager' of undefined],
JS:   [length]: 2 ]
JS: 'NativeScript-CameraPlus ---' [ '_initDefaultButtons error',
JS:   [Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
JS:       android.view.ViewConfiguration.get(ViewConfiguration.java:432)
JS:       android.view.View.<init>(View.java:4573)
JS:       android.view.View.<init>(View.java:4706)
JS:       android.widget.ImageView.<init>(ImageView.java:176)
JS:       android.widget.ImageButton.<init>(ImageButton.java:86)
JS:       android.widget.ImageButton.<init>(ImageButton.java:82)
JS:       android.widget.ImageButton.<init>(ImageButton.java:78)
JS:       android.widget.ImageButton.<init>(ImageButton.java:74)
JS:       com.tns.Runtime.callJSMethodNative(Native Method)
JS:       com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
JS:       com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
JS:       com.tns.Runtime.callJSMethod(Runtime.java:970)
JS:       com.tns.Runtime.callJSMethod(Runtime.java:954)
JS:       com.tns.Runtime.callJSMethod(Run...

any help, being waiting....
tks

**Comment by edwarchou** [comment]
I also register like this : 

Vue.registerElement('CameraPlus', () => require('@nstudio/nativescript-camera-plus').CameraPlus);

but it still doesn't work.
@bradmartin

**Comment by bradmartin** [comment]
This looks like it might be timing related. Are you using/showing the camera as the initial page in your application? It's possible it is being done before the app fully boots and NS has the android context to use this android API correctly.

**Comment by RaiserWeb** [comment]
When registering for Vue like this
`Vue.registerElement('CameraPlus', () => require('@nstudio/nativescript-camera-plus').CameraPlus);`
I'm getting the following error
`Failed to find @nstudio/nativescript-camera-plus module relative to app/tns_modules`
I've installed the package via npm, so the file is in node_modules. Not sure how/why it is looking in tns_modules (that folder doesn't exist).

**Comment by bradmartin** [comment]
Tns_modules is the directory made during a build for your app. You can find it inside the Android apk if you poke around. Not sure why you get that error though. Maybe it's a bundling issue if you have webpack working.
