### ISSUE TITLE
Hw to get rid off createImageConfirmationDialog

### ISSUE THREAD

**Issue by unkrautes** [nstudio/nativescript-camera-plus#35]
Hello,

I'm working with this Plug and its great just onething is giving me a headache. On Android after i took a picture come this little popup with says confirm or retake. I tried a few hours now to get rid of it somehw, I coulnd't figure it out! So please help :D

**Comment by unkrautes** [comment]
found the solutions just now

**Comment by Lelelo1** [comment]
There are currently properties on the CameraPlus object:

![confirm](https://user-images.githubusercontent.com/42244983/65581514-e526af80-df7b-11e9-9d80-331f420a2f9c.png)

But it does not work to set them to false? @unkrautes
