### ISSUE TITLE
Camera preview distorted

### ISSUE THREAD

**Issue by NewVote** [nstudio/nativescript-camera-plus#41]
I am using the demo code to implement a camera preview in my view, and the image is distorted (skewed)

![Skewed Camera](https://i.imgur.com/g1JTC9f.png)

Those are meant to be squares, and you can see in the captured image it is coming out OK. This warping is visible in a real device as well.

I am capturing with default options:
```
this.cam.takePicture({ saveToGallery: true });
```

I have tried setting the height and width myself in the CameraPlus component, but even forcing it to be a square (see example below) there is still some skewing.

```
<CameraPlus height="250"
    width="250"
    debug="true"
    galleryPickerMode="single"
    showFlashIcon="true"
    showToggleIcon="true"
    showCaptureIcon="true"
    showGalleryIcon="true"
    confirmSaveText="CONFIRM!"
    confirmRetakeText="RETAKE!"
    (loaded)="camLoaded($event)"
    (toggleCameraEvent)="toggleCameraEvent($event)"
    (photoCapturedEvent)="photoCapturedEvent($event)"
    (imagesSelectedEvent)="imagesSelectedEvent($event)">
</CameraPlus>
```

My goal is to have the preview display well at full screen width, with a set height (about 1/4 the screen)

**Comment by carrbrpoa** [comment]
Happens to me too

**Comment by felipebueno** [comment]
Same issue here!

**Comment by felipebueno** [comment]
In my case, it only happens when the camera is in fullscreen and the actionbar is hidden.

With Actionbar:
![with_action_bar](https://user-images.githubusercontent.com/241271/46954916-18707700-d068-11e8-8893-afb51085e32e.png)

Without Actionbar
![without_action_bar](https://user-images.githubusercontent.com/241271/46954934-21614880-d068-11e8-917b-5a3dbae44ede.png)

**Comment by felipebueno** [comment]
@bradmartin Can you help us on that? :smile:

**Comment by marcelofb** [comment]
Any news about this? Any way to fix it?

**Comment by bradmartin** [comment]
I am not 100% but I think something around this code [here](https://github.com/nstudio/nativescript-camera-plus/blob/master/src/camera-plus.android.ts#L1201) is what needs to be improved and worked on.

**Comment by bradmartin** [comment]
closing for now with 2.0.1 released with improvements in PR #60

**Comment by yesyo** [comment]
I'm pulling from master but still see the skewing happening. I'm testing on my Samsung S8.

Here's the screenshot:

![screenshot_20181227-090759_demo](https://user-images.githubusercontent.com/6957/50462411-b9a87180-09b7-11e9-9c3d-73f60d686624.jpg)

And here's the photo taken:

![img_1545876485367](https://user-images.githubusercontent.com/6957/50462420-cc22ab00-09b7-11e9-9209-8d47e56707a3.jpg)

Any idea?

**Comment by felipebueno** [comment]
Same here o/

**Comment by AntoineBouquet** [comment]
Same problem for me

**Comment by SweetMei25** [comment]
> But I could fix it by force the enableVideo to true
I enabled the enableVideo but didnt work.

**Comment by luiguild** [comment]
This problem continues when camera has in fullscreen, anyone already solved this?
