### ISSUE TITLE
Incompatibility with typescript 3.1.6

### ISSUE THREAD

**Issue by nickykln** [nstudio/nativescript-camera-plus#55]
Hi, 

I am trying to use your plugin within my project and I get the following error by only importing your module

import { CameraPlus } from '@nstudio/nativescript-camera-plus';

ERROR in node_modules/@nstudio/nativescript-camera-plus/index.d.ts(58,43): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/@nstudio/nativescript-camera-plus/index.d.ts(63,47): error TS1039: Initializers are not allowed in ambient contexts.

I am using the TypeScript Version 3.1.6. I guess this is the issue.
Does anyone has the same issue ? Is there a workaround ?

Thanks a lot,

N

**Comment by NathanWalker** [comment]
Thanks for reporting this @nickykln we’ll publish a fix for this today.

**Comment by NathanWalker** [comment]
@nickykln fix should be published in `1.1.3` now 👍

**Comment by nickykln** [comment]
@NathanWalker Thanks a lot for this quick answer and this even quicker fix.

N
