### ISSUE TITLE
problem with LG

### ISSUE THREAD

**Issue by marcelofb** [nstudio/nativescript-camera-plus#56]
Hi, I'm wanting to use the plugin in a LG Q6 cell phone and when I open the camera I get the following error

![screenshot_2018-11-13-12-42-03](https://user-images.githubusercontent.com/10368592/48424741-0145a780-e742-11e8-905e-571983c209a0.png)

How could I solve this problem?

Thanks!

**Comment by triniwiz** [comment]
Fixed: b24997c feel free to reopen :- update to 3.1.x
