### ISSUE TITLE
Android constant RESULT_CODE_PICKER_IMAGES is too high

### ISSUE THREAD

**Issue by jkod** [nstudio/nativescript-camera-plus#58]
I'm trying the demo code in a NS 5 project, and when I use the function `chooseFromLibrary ` on Android I am getting the following error:

JS: ERROR Error: Uncaught (in promise): Error: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
JS:     android.support.v4.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:806)
JS:     android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:967)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:959)
JS:     com.tns.gen.java.lang.Object_vendor_97559_32_ClickListenerImpl.onClick(Object_vendor_97559_32_ClickListenerImpl.java:17)
JS:     android.view.View.performClick(View.java:6256)
JS:     android.view.View$PerformClick.run(View.java:24697)
JS:     android.os.Handler.handleCallback(Handler.java:789)
JS:     android.os.Handler.dispatchMessage(Handler.java:98)
JS:     android.os.Looper.loop(Looper.java:1...

It is apparently a limit set in the Android support library, and this throws an exception as it is currently set to `415161`.

More info: https://stackoverflow.com/a/33331459/4747587

**Comment by jorgeartigas** [comment]
same issue
