### ISSUE TITLE
camera cannot take image after i use bluetooth on notify

### ISSUE THREAD

**Issue by norainmatidris** [nstudio/nativescript-camera-plus#61]
Hi , i was going to do something like when i click on Bluetooth button, it will get the this.cam.takepicture. 
but i facing the problem. 

### **it appeared error like this.** 

System.err: com.tns.NativeScriptException:
System.err: Calling js method onCharacteristicChanged failed
System.err: TypeError: Cannot read property 'takePicture' of undefined
System.err: File: "file:///data/data/org.nativescript.Beacon/files/app/page/fancyCamera.page.js, line: 14, column: 21
System.err: StackTrace:
System.err:     Frame: function:'FancyCameraPageComponent.onData', file:'file:///data/data/org.nativescript.Beacon/files/app/page/fancyCamera.page.js', line: 14, column: 22
System.err:     Frame: function:'onCharacteristicChanged', file:'file:///data/data/org.nativescript.Beacon/files/app/tns_modules/nativescript-bluetooth/bluetooth.js', line: 348, column: 19
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.access$2300(Runtime.java:34)
System.err:     at com.tns.Runtime$3.run(Runtime.java:1112)
System.err:     at android.os.Handler.handleCallback(Handler.java:733)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:149)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5061)
System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
System.err:     at dalvik.system.NativeStart.main(Native Method)
ActivityManager: Process org.nativescript.Beacon (pid 7745) has died.

### **here is my code.**

startNotifyButton(){
    bluetooth.startNotifying({
        peripheralUUID: "FF:FF:90:01:B1:EF",
        serviceUUID: "ffe0", 
        characteristicUUID: "ffe1",
        onNotify: function (result) {
            try
            {
                var data = new Uint8Array(result.value);
                console.log('notify: '+JSON.stringify(data));
                this.cam.takePicture({ saveToGallery: true });
            }
            catch(e)
            {
                alert('notify value not readable: '+e.message);
            }
}).then(function() {
        console.log("subscribed for notifications");
        });
}

**Comment by bradmartin** [comment]
Might be a JS scope issue. What does `this` log out inside your `try/catch` in the `startNotifying() method. Have you tried using arrow functions for making sure you are getting the correct `this` instance? Just a guess looking at the code. Could be something else entirely, but I lean toward cleaning up the code first and seeing what `this` is with your current logic.

**Comment by norainmatidris** [comment]
@bradmartin hi.. this is my whole code. can you help me ? 

import { Component, OnDestroy, OnInit, ViewChild, ElementRef, NgZone } from "@angular/core";
import { RouterExtensions } from 'nativescript-angular/router';
import { Page } from 'tns-core-modules/ui/page';
import { CameraPlus } from '@nstudio/nativescript-camera-plus';
import { ImageSource } from 'tns-core-modules/image-source';
import { ImageAsset } from 'tns-core-modules/image-asset';
import { Image } from 'tns-core-modules/ui/image';
import { FancyCamera } from 'nativescript-fancy-camera';
var bluetooth = require("nativescript-bluetooth");

@Component({
    moduleId: module.id,
    selector: "ns-fancyCamera.page",
    templateUrl: "fancyCamera.page.html",
    styleUrls: ['/../app.css'],
    
})

export class FancyCameraPageComponent  implements OnInit, OnDestroy {
 fc = new FancyCamera();

 private cam: CameraPlus;
 public imageSource: ImageSource;


 constructor(private zone: NgZone) {

 }

 ngOnInit(): void {
 }
 
 ngOnDestroy() {
 }

 camLoaded(e: any): void {
    console.log('***** cam loaded *****');
    this.cam = e.object as CameraPlus;
    let flashMode = this.cam.getFlashMode();
    // Turn flash on at startup
    if (flashMode == 'off') {
        this.cam.toggleFlash();
    }
    // TEST THE ICONS SHOWING/HIDING
    // this.cameraPlus.showCaptureIcon = true;
    // this.cameraPlus.showFlashIcon = true;
    // this.cameraPlus.showGalleryIcon = false;
    // this.cameraPlus.showToggleIcon = false;
}
imagesSelectedEvent(e: any): void {
    console.log('IMAGES SELECTED EVENT!!!');
    this.loadImage((e.data as ImageAsset[])[0]);
}

photoCapturedEvent(e: any): void {
    console.log('PHOTO CAPTURED EVENT!!!');
    this.loadImage(e.data as ImageAsset);

} 


toggleCameraEvent(e: any): void {
    console.log("camera toggled");
}


recordDemoVideo(): void {
    try {
        console.log(`*** start recording ***`);
        this.cam.record();
    } catch (err) {
        console.log(err);
    }
}


stopRecordingDemoVideo(): void {
    try {
        console.log(`*** stop recording ***`);
        this.cam.stop();
        console.log(`*** after this.cam.stop() ***`);
    } catch (err) {
        console.log(err);
    }
}


toggleFlashOnCam(): void {
    this.cam.toggleFlash();
}


toggleShowingFlashIcon(): void {
    console.log(`showFlashIcon = ${this.cam.showFlashIcon}`);
    this.cam.showFlashIcon = !this.cam.showFlashIcon;
}


toggleTheCamera(): void {
    this.cam.toggleCamera();
}

openCamPlusLibrary(): void {
    this.cam.chooseFromLibrary();
}

takePicFromCam(): void {
    this.cam.takePicture({ saveToGallery: true });
}

startNotifyButton(){
    bluetooth.startNotifying({
        peripheralUUID: "FF:FF:90:01:B1:EF",
        serviceUUID: "ffe0", 
        characteristicUUID: "ffe1",
        onNotify: this.onData
        /*
        onNotify: function (result) {
            try
            {
                var data = new Uint8Array(result.value);
                console.log('notify: '+JSON.stringify(data));
                this.cam.takePicture({ saveToGallery: true });
            }
            catch(e)
            {
                alert('notify value not readable: '+e.message);
            }

        }   */ 
}).then(function() {
        console.log("subscribed for notifications");
        
        });
} 

onData = function (result) {
    var data = new Uint8Array(result.value);
    console.log('notify: '+data);
    this.takePicFromCamButton
   /* if (data[0]=1){
        this.cam.takePicture({ saveToGallery: true });
    }*/
  }
 
takePicFromCamButton(): void {
    console.log("get this functions");
   //this.cam.takePicture({ saveToGallery: true });
}
 
loadImage(imageAsset: ImageAsset): void {
    if (imageAsset) {
        this.imageSource = new ImageSource();
        this.imageSource.fromAsset(imageAsset).then(
            (imgSrc) => {
                if (imgSrc) {
                    this.zone.run(() => {
                     this.imageSource = imgSrc;
                    })
                } else {
                    this.imageSource = null;
                    alert('Image source is bad.');
                }
            },
            (err) => {
                this.imageSource = null;
                console.log('Error getting image source: ')
                console.error(err);
                alert('Error getting image source from asset');
            }
        )
    } else {
        console.log('Image Asset was null')
        alert('Image Asset was null');
        this.imageSource = null;
    }
}
}

**Comment by norainmatidris** [comment]
`import { Component, OnDestroy, OnInit, ViewChild, ElementRef, NgZone } from "@angular/core";
import { RouterExtensions } from 'nativescript-angular/router';
import { Page } from 'tns-core-modules/ui/page';
import { CameraPlus } from '@nstudio/nativescript-camera-plus';
import { ImageSource } from 'tns-core-modules/image-source';
import { ImageAsset } from 'tns-core-modules/image-asset';
import { Image } from 'tns-core-modules/ui/image';
import { FancyCamera } from 'nativescript-fancy-camera';
var bluetooth = require("nativescript-bluetooth");

@Component({
    moduleId: module.id,
    selector: "ns-fancyCamera.page",
    templateUrl: "fancyCamera.page.html",
    styleUrls: ['/../app.css'],
    
})

export class FancyCameraPageComponent  implements OnInit, OnDestroy {
 fc = new FancyCamera();

 private cam: CameraPlus;
 public imageSource: ImageSource;


 constructor(private zone: NgZone) {

 }

 ngOnInit(): void {
 }
 
 ngOnDestroy() {
 }

 camLoaded(e: any): void {
    console.log('***** cam loaded *****');
    this.cam = e.object as CameraPlus;
    let flashMode = this.cam.getFlashMode();
    // Turn flash on at startup
    if (flashMode == 'off') {
        this.cam.toggleFlash();
    }
    // TEST THE ICONS SHOWING/HIDING
    // this.cameraPlus.showCaptureIcon = true;
    // this.cameraPlus.showFlashIcon = true;
    // this.cameraPlus.showGalleryIcon = false;
    // this.cameraPlus.showToggleIcon = false;
}
imagesSelectedEvent(e: any): void {
    console.log('IMAGES SELECTED EVENT!!!');
    this.loadImage((e.data as ImageAsset[])[0]);
}

photoCapturedEvent(e: any): void {
    console.log('PHOTO CAPTURED EVENT!!!');
    this.loadImage(e.data as ImageAsset);

} 


toggleCameraEvent(e: any): void {
    console.log("camera toggled");
}


recordDemoVideo(): void {
    try {
        console.log(`*** start recording ***`);
        this.cam.record();
    } catch (err) {
        console.log(err);
    }
}


stopRecordingDemoVideo(): void {
    try {
        console.log(`*** stop recording ***`);
        this.cam.stop();
        console.log(`*** after this.cam.stop() ***`);
    } catch (err) {
        console.log(err);
    }
}


toggleFlashOnCam(): void {
    this.cam.toggleFlash();
}


toggleShowingFlashIcon(): void {
    console.log(`showFlashIcon = ${this.cam.showFlashIcon}`);
    this.cam.showFlashIcon = !this.cam.showFlashIcon;
}


toggleTheCamera(): void {
    this.cam.toggleCamera();
}

openCamPlusLibrary(): void {
    this.cam.chooseFromLibrary();
}

takePicFromCam(): void {
    this.cam.takePicture({ saveToGallery: true });
}

startNotifyButton(){
    bluetooth.startNotifying({
        peripheralUUID: "FF:FF:90:01:B1:EF",
        serviceUUID: "ffe0", 
        characteristicUUID: "ffe1",
        onNotify: this.onData
        /*
        onNotify: function (result) {
            try
            {
                var data = new Uint8Array(result.value);
                console.log('notify: '+JSON.stringify(data));
                this.cam.takePicture({ saveToGallery: true });
            }
            catch(e)
            {
                alert('notify value not readable: '+e.message);
            }

        }   */ 
}).then(function() {
        console.log("subscribed for notifications");
        
        });
} 

onData = function (result) {
    var data = new Uint8Array(result.value);
    console.log('notify: '+data);
    this.takePicFromCamButton
   /* if (data[0]=1){
        this.cam.takePicture({ saveToGallery: true });
    }*/
  }
 
takePicFromCamButton(): void {
    console.log("get this functions");
   //this.cam.takePicture({ saveToGallery: true });
}
 
loadImage(imageAsset: ImageAsset): void {
    if (imageAsset) {
        this.imageSource = new ImageSource();
        this.imageSource.fromAsset(imageAsset).then(
            (imgSrc) => {
                if (imgSrc) {
                    this.zone.run(() => {
                     this.imageSource = imgSrc;
                    })
                } else {
                    this.imageSource = null;
                    alert('Image source is bad.');
                }
            },
            (err) => {
                this.imageSource = null;
                console.log('Error getting image source: ')
                console.error(err);
                alert('Error getting image source from asset');
            }
        )
    } else {
        console.log('Image Asset was null')
        alert('Image Asset was null');
        this.imageSource = null;
    }
}
}`

**Comment by NathanaelA** [comment]
@norainmatidris - this is a scope issue; `this` is not defined at that point inside of ondata.   You can try a couple things to fix your scope; but this is probably the simplist:  `onNotify: this.onData.bind(this)`
