### ISSUE TITLE
(Android) Live preview delay on taking image

### ISSUE THREAD

**Issue by jackbayliss** [nstudio/nativescript-camera-plus#62]
Hi, when using this on an Android device (Samsung S6 edge) I noticed there's around a 1-3 second delay on the actual preview when taking a picture. Is there anything we can to do reduce the delay? 

I assumed it may have been the confirmation dialog. But it still has a few seconds delay with `cam.takePicture({confirm: false});` 

Thanks,

Jack

**Comment by jackbayliss** [comment]
Not sure if this is also related to the Android camera1 API being deprecated. And the phones > Android 5.0.
*Closing issue as no longer a problem for me, fixed with alternative camera library.

**Comment by Bezlepkin** [comment]
> Not sure if this is also related to the Android camera1 API being deprecated. And the phones > Android 5.0.
> *Closing issue as no longer a problem for me, fixed with alternative camera library.

Hi!I have same problem. What alternative camera library?

**Comment by jackbayliss** [comment]
@Bezlepkin I switched to use Ionic Angular instead. I couldn't figure a way around this.
