### ISSUE TITLE
Error trying the demo

### ISSUE THREAD

**Issue by darknd** [nstudio/nativescript-camera-plus#67]
Before 'npm run demo.ng.ios.device'

Installing pods...
Analyzing dependencies
Pre-downloading: `SwiftyCam` from `https://github.com/NathanWalker/SwiftyCam.git`
Downloading dependencies
Installing QBImagePickerController (3.4.0)
Installing SwiftyCam (2.3.1)
[!] Unable to determine Swift version for the following pods:

- `SwiftyCam` does not specify a Swift version and none of the targets (`demong`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by Kralyc** [comment]
i got the same error!! i have a nativescript proyect, the plugin works fine with android but when i try use it on iphone i can't

**Comment by NathanWalker** [comment]
Thanks for this report, we'll get a fix posted this week.

**Comment by NathanWalker** [comment]
@Kralyc @darknd `2.1.0` should have this fix now. Also if you pull latest master you should be able to run the demo. Just clear things locally when you pull:
```
cd src
rm -rf node_modules package-lock.json
cd ../demo
rm -rf node_modules package-lock.json platforms
cd ../demo-ng
rm -rf node_modules package-lock.json platforms
cd ../src
npm run build
npm run demo.ios
```
Just keep in mind you need to run on real device to try out the camera features.
