### ISSUE TITLE
IOS -  this.takePhoto is not a function

### ISSUE THREAD

**Issue by SerAlalal** [nstudio/nativescript-camera-plus#69]
in the MySwifty.prototype.snapPicture
error 
this.takePhoto is not a function  (line 242)

**Comment by Stilleur** [comment]
Would you check if this answer help you out ?

https://github.com/nstudio/nativescript-camera-plus/issues/70#issuecomment-470192010

**Comment by AquilesOliveira** [comment]
Problem solved in this new version 2.1.1
