### ISSUE TITLE
Feedback: Awesome Work. 

### ISSUE THREAD

**Issue by hainakus** [nstudio/nativescript-camera-plus#8]
Hi there. 

Great Job on the plugin!!

**Comment by hainakus** [comment]
Just a question... takepicture method is on CameraPlus class but cannot work it out so i can put another button and take photo.

My aim is to take several photos in a setinterval

**Comment by bradmartin** [comment]
The demo might help you out here:
https://github.com/nstudio/nativescript-camera-plus/blob/master/demo/app/main-page.xml#L39
Grab your camera instance: https://github.com/nstudio/nativescript-camera-plus/blob/master/demo/app/main-view-model.ts#L21
And the bound function to a buttons tap event: https://github.com/nstudio/nativescript-camera-plus/blob/master/demo/app/main-view-model.ts#L126 which calls `takePicture`. Then we use the event listeners event here `https://github.com/nstudio/nativescript-camera-plus/blob/master/demo/app/main-view-model.ts#L38` on our instance to get the result.

**Comment by hainakus** [comment]
Hi. thanks for feedback. working on angular nativescript and calling the camera instance on. But... no photo.
import { CameraPlus } from "@nstudio/nativescript-camera-plus";
 constructor(private cam:CameraPlus, private fonticon: TNSFontIconService, private renderer: Renderer){

    }

fabTap(event){
        /*this.cam.record()
        if(CameraPlus.enableVideo){
            
            this.camPluschild.nativeElement.on(CameraPlus.videoRecordingFinishedEvent, args => {
                console.log(args);
            })
        }*/
  
       var opts = {
        saveToGallery: false,
        confirm:  false,
        autoSquareCrop: true
    };
    this.cam.takePicture(opts)
      
      
    }

**Comment by bradmartin** [comment]
How are you getting the `cam`? I see in the constructor you have a ref, but are you grabbing it via its `id (#)` from the template? Seeing more of the code might help some.

**Comment by hainakus** [comment]
the cam view from  @ViewChild("camPlus") camPlus: ElementRef;

this.cam : CameraPlus on constructor (private cam: CameraPlus)

**Comment by bradmartin** [comment]
K, then would it be `this.camPlus.takePicture` and not `this.cam` because your ElementRef gets the instance from the template? I'm going from memory here :) so don't hold this to me

**Comment by hainakus** [comment]
Hi Brad. thanks but no. I can only access the takepicture(opts) from this.cam . I think its cause the takepicture method needs the camera on plugin to be initiated as far i saw. that's why it says null on console log. But i might be wrong.

this is the full code from the angular:


        import { Component, ElementRef, ViewChild, OnInit, AfterViewInit, Renderer } from "@angular/core";
        import { CameraPlus } from "@nstudio/nativescript-camera-plus";
        import { registerElement } from "nativescript-angular/element-registry";
        registerElement("CameraPlus", () => <any>CameraPlus);
        registerElement("Fab", () => require("nativescript-floatingactionbutton").Fab);
        import { fromAsset } from "tns-core-modules/image-source";
        import * as platformModule from "tns-core-modules/platform";
        import { TNSFontIconService } from 'nativescript-ng2-fonticon';
        declare var android:any;
        @Component({
            selector: "ns-app",
            templateUrl: "app.component.html",
        })

        export class AppComponent implements OnInit, AfterViewInit {
            @ViewChild("camPlus") camPlus: ElementRef;
            @ViewChild("camButton") camButton: ElementRef;
            width:number = platformModule.screen.mainScreen.widthPixels;
            height:number = platformModule.screen.mainScreen.heightPixels;
            constructor(private cam:CameraPlus, private fonticon: TNSFontIconService, private renderer: Renderer){

            }

            ngOnInit(){
            
                this.camPlus.nativeElement.on(CameraPlus.photoCapturedEvent, args => {
                    console.log(args);
                    fromAsset(args.data)
                    .then(res => {
                        console.log("res", res);
                    })
                    .catch(err => {
                        console.log("err", err);
                    });
                });
        
            }
            ngAfterViewInit(){

            }
            fabTap(event){
                /*this.cam.record()
                if(CameraPlus.enableVideo){
                    
                    this.camPluschild.nativeElement.on(CameraPlus.videoRecordingFinishedEvent, args => {
                        console.log(args);
                    })
                }*/
        
            var opts = {
                saveToGallery: false,
                confirm:  false,
                autoSquareCrop: true
            };
        
            
            this.cam.takePicture(opts)
            }
        }
````_

**Comment by hainakus** [comment]
Sorry for my mistake.. its perfect PLugin!!!

my code... it works pretty well,


--- View -- 

                    <ActionBar title="Details" class="action-bar"></ActionBar>
            <FlexboxLayout flexDirection="column" class="page">
                <CameraPlus #camPlus debug="true" height="{{cameraHeight}}"
                confirmPhotos="true"
                showToggleIcon="false"
                showCaptureIcon="true"
                showFlashIcon="true"
                showGalleryIcon="false">
            
                
                
                
                </CameraPlus>
                <button #camButton (tap)="takePicFromCam()">toogle</button>
                
            </FlexboxLayout>


--- controller ----
        import { Component, ElementRef, ViewChild, OnInit, AfterViewInit, Renderer } from "@angular/core";
       
        import { CameraPlus } from "@nstudio/nativescript-camera-plus";
        import { registerElement } from "nativescript-angular/element-registry";
        registerElement("CameraPlus", () => <any>CameraPlus);
        registerElement("Fab", () => require("nativescript-floatingactionbutton").Fab);
        import { fromAsset } from "tns-core-modules/image-source";
        import * as platformModule from "tns-core-modules/platform";
        import { TNSFontIconService } from 'nativescript-ng2-fonticon';
      
        import { Page } from "tns-core-modules/ui/page";
        import { ImageAsset } from "tns-core-modules/image-asset";
        import { topmost } from "tns-core-modules/ui/frame";
        import { Image } from "tns-core-modules/ui/image";
      
        @Component({
            selector: "ns-app",
            templateUrl: "app.component.html",
        })

        export class AppComponent extends Observable implements OnInit, AfterViewInit  {
           
            private _counter: number = 0;
            @ViewChild('camPlus') cameera : ElementRef
           public cam: CameraPlus;
           public cameraHeight: number;
            width:number = platformModule.screen.mainScreen.widthPixels;
            height:number = platformModule.screen.mainScreen.heightPixels;
            constructor(private fonticon: TNSFontIconService, private renderer: Renderer, page:Page){
                super()
               
                this.cameraHeight = platformModule.screen.mainScreen.heightDIPs * 0.45;

               
            }
            ngAfterViewInit(){
              this.cam = this.cameera.nativeElement as CameraPlus;
            }
            ngOnInit(){
                // hide a default icon button here
                // this.cam.showGalleryIcon = false
                if (this._counter > 0) {
                  return;
                }
            
                this.cam.on(CameraPlus.errorEvent, args => {
                  console.log("*** CameraPlus errorEvent ***", args);
                });
            
                this.cam.on(CameraPlus.toggleCameraEvent, (args: any) => {
                  console.log(`toggleCameraEvent listener on main-view-model.ts  ${args}`);
                });
            
                this.cam.on(CameraPlus.photoCapturedEvent, (args: any) => {
                  console.log(`photoCapturedEvent listener on main-view-model.ts  ${args}`);
                  console.log((<any>args).data);
                  fromAsset((<any>args).data).then(res => {
                    const testImg = topmost().getViewById("testImagePickResult") as Image;
                    testImg.src = res;
                  });
                });
            
                this.cam.on(CameraPlus.imagesSelectedEvent, (args: any) => {
                  console.log(`imagesSelectedEvent listener on main-view-model.ts ${args}`);
                });
            
                this.cam.on(CameraPlus.videoRecordingReadyEvent, (args: any) => {
                  console.log(`videoRecordingReadyEvent listener fired`, args.data);
                });
            
                this.cam.on(CameraPlus.videoRecordingStartedEvent, (args: any) => {
                  console.log(`videoRecordingStartedEvent listener fired`, args.data);
                });
            
                this.cam.on(CameraPlus.videoRecordingFinishedEvent, (args: any) => {
                  console.log(`videoRecordingFinishedEvent listener fired`, args.data);
                });
            
                this._counter = 1;
              }
            
              public recordDemoVideo() {
                try {
                  console.log(`*** start recording ***`);
                  this.cam.record();
                } catch (err) {
                  console.log(err);
                }
              }
            
              public stopRecordingDemoVideo() {
                try {
                  console.log(`*** stop recording ***`);
                  this.cam.stop();
                  console.log(`*** after this.cam.stop() ***`);
                } catch (err) {
                  console.log(err);
                }
              }
            
              public toggleFlashOnCam() {
                this.cam.toggleFlash();
              }
            
              public toggleShowingFlashIcon() {
                console.log(`showFlashIcon = ${this.cam.showFlashIcon}`);
                this.cam.showFlashIcon = !this.cam.showFlashIcon;
              }
            
              public toggleTheCamera() {
                this.cam.toggleCamera();
              }
            
              public openCamPlusLibrary() {
                this.cam.chooseFromLibrary().then(
                  (images: Array<ImageAsset>) => {
                    console.log("Images selected from library total:", images.length);
                    for (let source of images) {
                      console.log(`source = ${source}`);
                    }
                    const testImg = topmost().getViewById("testImagePickResult") as Image;
                    const firstImg = images[0];
                    console.log(firstImg);
                    fromAsset(firstImg)
                      .then(res => {
                        const testImg = topmost().getViewById(
                          "testImagePickResult"
                        ) as Image;
                        testImg.src = res;
                      })
                      .catch(err => {
                        console.log(err);
                      });
                  },
                  err => {
                    console.log("Error -> " + err.message);
                  }
                );
              }
            
              public takePicFromCam() {
                this.cam.takePicture({ saveToGallery: true });
              }
            }

**Comment by hainakus** [comment]
@bradmartin please close this issue. it was a simple instance initiation on angular that should be on ngAFterViewInit(){}
