### ISSUE TITLE
Custom Layout on iOS not Visible

### ISSUE THREAD

**Issue by Logikgate** [nstudio/nativescript-camera-plus#80]
This is possibly related to #75 but I am unable to test on android right now.

As of version 2.1.1 any custom layout that is included within CameraPlus is not visible in iOS.  I have tracked down the issue and it is related to the view type that CameraPlusBase extends. Prior to v2.1.1 CameraPlusBase extended ContentView but [it now extends View](https://github.com/nstudio/nativescript-camera-plus/blob/b3494e9196c84bbdb3f73d16e2e39f378ada341f/src/camera-plus.common.ts#L7).

By changing back to extending ContentView custom layouts in iOS [appear to be working](https://github.com/flypapertech/nativescript-camera-plus/commit/dbc4575aee151a143aa7b0652c174d7554faf16a).  @triniwiz or @NathanWalker before I make a pull request is there a reason I'm not seeing that makes extending View required?

**Comment by triniwiz** [comment]
You tried setting a size ?

**Comment by Logikgate** [comment]
By size what are you referring to? I am setting a height and width for the CameraPlus.  The below markup shows the camera but no button currently but when ContentView is used the button is visible, is there some size I'm not setting?

`CameraPlus(@loaded="cameraLoaded" debug="true" :height="cameraHeight" :width="cameraWidth" :enableVideo="true" galleryPickerMode="multiple" :saveToGallery="saveToGallery" :showCaptureIcon="false" :showGalleryIcon="false" :showToggleIcon="false" :showFlashIcon="false" :confirmPhotos="reviewMode")
    StackLayout
        Button(:text="cameraIcon" @tap="flipCamera").mdi.display-1.mx-1`

**Comment by s3477631** [comment]
I found it doesn't work on android either (nesting an overlay or image inside of CameraPlus tags)

**Comment by kdagnan** [comment]
Did we ever figure this out @Logikgate @triniwiz ? I am also unable to get custom layouts to work.

**Comment by Logikgate** [comment]
This has been resolved as of version 2.2.0 due to pull request #88.  Thanks @kdagnan for opening the pull request for me 👍
