### ISSUE TITLE
[Android] The Camera preview screen looks taller than original.

### ISSUE THREAD

**Issue by SweetMei25** [nstudio/nativescript-camera-plus#84]
Preview Screenshot:
https://drive.google.com/file/d/1ojkWo0hQaHPxXe86PvtmW1e9IAfcxv9j/view?usp=sharing
Actual Image:
https://drive.google.com/file/d/1GnDBjjFpHadfaHxCfaIESqnv4TPTCw7E/view?usp=sharing

I just saw that this issue is fixed but actually, this isn't fixed.

**Comment by anireddysaikumar** [comment]
Same issue for me, especially width is cutting from both left and right, any way to fix it. please help me.

**Comment by shiv19** [comment]
Closed as the issue was reported to be resolved by @SweetMei25

**Comment by anireddysaikumar** [comment]
@shiv19 @SweetMei25  this issue is still happening for me. Can you please help me on it.

**Comment by PabloPG** [comment]
Did they fix it?
