### ISSUE TITLE
Real time camera view is not displaying the correct aspect ratio and also result is always cropped from the center. 

### ISSUE THREAD

**Issue by AsrarMemon** [nstudio/nativescript-camera-plus#96]
Hello,

we are using your library in one of our applications to allow users to capture profile pictures.

Our Requirements:

1) We want to show a realtime camera view to the user (We are using the <CameraPlus> Tag for the same)
2) With a button press he should be able to take a picture
3) We want to display the result image/picture to the user for verification (We are using the output of .takePicture).

We are facing the following issues with this library (as per our requirement).
1) Sometimes the real time camera view is not displaying the correct aspect ratio, as shown in below screenshots:
![huawei p9 capture](https://user-images.githubusercontent.com/24634005/62368640-ce9b4380-b54a-11e9-8fe1-bba170db8756.png)

2) When we use the autoSquareCrop option with <CameraPlus> Tag the images is always cropped from the center. 
You can see the issue in the below screenshots:

Original camera image:
![samsung a5 capture](https://user-images.githubusercontent.com/24634005/62368677-ea9ee500-b54a-11e9-85c6-3800aa4664ad.jpg)

Output coming from CameraPlus:
![samsung a5 preview](https://user-images.githubusercontent.com/24634005/62368681-effc2f80-b54a-11e9-9769-f1298867f86c.jpg)

We would like to crop either image height or width. E.g. if captured image width < height then width must remain same and height should be cropped from top 
and bottom to maintain its Aspect Ratio. Same way if captured image width > height then height must remain same and width will cropped from left and right to maintain its Aspect Ratio.
for handlig above requirement we are calling takePicture method like 
this.cam.takePicture({ saveToGallery: true ,autoSquareCrop:true});

We are passing parameter to this library as,
in .html file =>
`
<CameraPlus height="300" width="300" galleryPickerMode="single" showFlashIcon="false" showToggleIcon="false"
 showCaptureIcon="false" showGalleryIcon="false" confirmSaveText="CONFIRM!" confirmRetakeText="RETAKE!"
 (loaded)="camLoaded($event)" (photoCapturedEvent)="photoCapturedEvent($event)"
 (imagesSelectedEvent)="imagesSelectedEvent($event)" >
 </CameraPlus>
`

and from .ts file =>
`
this.cam.takePicture({saveToGallery: true});
`

`
public photoCapturedEvent(e: any): void {
 this.loadImage(e.data as ImageAsset);//this is our method where we set image asset to preview/result 
}
`

Thanks in advance!
Regards,
Asrar

**Comment by zoocreative** [comment]
You can manually crop the image if you use something like BitmapFactory. Although I am also seeing the distorted preview and would love to know how to fix it for taking square photos in preview.

**Comment by joshcomley** [comment]
I also am unsure how to make the realtime camera preview show the correct aspect ratio for the device's camera. I can't find any info on how to get the aspect ratio of the device's cameras via NativeScript, either.

**Comment by RosilBelli** [comment]
I'm facing the exact same issue on my app without any clue on how to change the camera aspect ratio nether solve this distortion on camera view.

**Comment by zoocreative** [comment]
I had to edit the pluign to give me the optimal size of the image and then using that to calculate the ratio of the camera and then use that to size the camera preview. I let it fill the screen and then used additional images to block out anyof the camera view I didn't want i.e. to make it look square. It's a bit of a workaround but it seems to work.
However, it's still not 100% as some people are still getting distortion issues. But it seems to be working on most platforms.

**Comment by triniwiz** [comment]
Fixed: https://github.com/nstudio/nativescript-camera-plus/commit/b24997c918df8ceafb73443708a58708be46d5ed feel free to reopen :- update to `3.1.x`
