### ISSUE TITLE
How it's possible use get/setParameters in Vue?

### ISSUE THREAD

**Issue by luiguild** [nstudio/nativescript-camera-plus#99]
actually I have this scenario

```
<template>
...
<CameraPlus
  v-if="permission"
  height="550"
  debug="true"
  galleryPickerMode="single"
  showFlashIcon="false"
  showToggleIcon="true"
  showCaptureIcon="true"
  showGalleryIcon="false"
  defaultCamera="front"
  @loaded="doCamLoaded"
></CameraPlus>
...
</template>
<script>
...
methods: {
  doCamLoaded (event) {
    this.cam = event.object
    const parameters = this.cam.getParameters()
  }
}
...
</script>
```

I just need read the camera's parameters and set some changes onthefly... But looks to be impossible... How i can proceed with this? thx

**Comment by triniwiz** [comment]
Not supported again the camera uses a mix of the [Camera1 API](https://developer.android.com/guide/topics/media/camera) and the new [CameraX API](https://developer.android.com/training/camerax) wrapped with [this](https://github.com/triniwiz/fancycamera)
